"use strict";

export const HOTEL_SEARCH_REQUEST       = 'HOTEL_SEARCH_REQUEST';
export const HOTEL_SEARCH_SUCCESS       = 'HOTEL_SEARCH_SUCCESS';
export const HOTEL_SEARCH_SORT_BY_PRICE = 'HOTEL_SEARCH_SORT_BY_PRICE';
